### ISSUE TITLE
反馈几个bug

### ISSUE THREAD

**Issue by Atrium4641** [sparkbridge/sparkbridge2#11]
![d941e8dd03f406d340ca62298398df59](https://github.com/user-attachments/assets/75cde27a-e9c6-48d7-94ab-fa4011dd3ab4)

怎么这个GetMsgPack写了两遍

![7e3ed3b8cbf84976c7f7a87f8447b81d](https://github.com/user-attachments/assets/35e46c43-04e5-4d29-a8a3-a42b72a767c8)

这个SB的API文档上写了，但是我看packbuilder.js里根本没有

![9e0762f050d54adeb9b147096bb24a54](https://github.com/user-attachments/assets/7a8fa846-ea78-4b29-8568-4f4f12c46f2f)
![a6deed260d1f456ee21b5a370a8de62c](https://github.com/user-attachments/assets/ef54ffb3-2f33-44f3-89b6-ebbd2ffcacc5)
这个packbuilder.js里的GroupMemberInfoPack格式好像不对

![283226ecc3ee13bca42b2fc4e6e41060](https://github.com/user-attachments/assets/4a89301c-fe34-4e25-b631-8af1da33f6f2)
这个玩意一开，机器人就总是自己撤回自己的消息

**Comment by DanielToyama** [comment]
群成员信息没写错；撤回信息不是框架问题
剩余问题已修复
